version: "3"
containers:
- name: container
  image: fedora
  shell: /bin/bash
virtualmachines:
- name: crc
  image: openshift-instruqt/openshift-instruqt-crc490-211026
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
# - name: spoke
#   #image: megatron-198805/openshift-sno-v5
#   image: megatron-198805/openshift-sno-v4
#   #image: megatron-198805/openshift-sno02-v1
#   #image: centos-cloud/centos-stream-8
#   machine_type: n1-standard-16
#   allow_external_ingress:
#   - http
#   - https
#   - high-ports
- name: spoke
  image: instruqt/k3s-v1-25-0
  shell: /bin/bash
  environment:
    K3S_TOKEN: superSecur3T0ken
  machine_type: n1-standard-1  